### PR TITLE
Coidb

### PR DESCRIPTION
**Pull request by johnne**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by johnne** [comment]
Adds a [COI database](https://figshare.scilifelab.se/articles/dataset/COI_reference_sequences_from_BOLD_DB/20514192) to reference databases.

**Comment by erikrikarddaniel** [comment]
Weird that it fails with the standard test data. What happened to formatting of that with the change of container? Do the tests pass for you?

**Comment by johnne** [comment]
@erikrikarddaniel I hadn't synced my fork completely I realized. Rerunning tests locally no also

**Comment by erikrikarddaniel** [comment]
The tests didn't restart, right, or did they fail again @johnne?

**Pull request closed without merging**
